spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/meu-projeto-social-db
    username:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
